CREATE TABLE "EVALUATIONS" (
    "DIPLOM" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TEACHER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CRITERIA" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"POINTS" NUMBER(2,0) NOT NULL ENABLE, 
	
	CONSTRAINT "EVALUATIONS_PK" PRIMARY KEY ("DIPLOM", "TEACHER", "CRITERIA")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	
    CONSTRAINT "EVALUATIONS_CRITERIAS_FK1" FOREIGN KEY ("CRITERIA")
	REFERENCES "CRITERIAS" ("TITLE") ENABLE, 
	
	CONSTRAINT "EVALUATIONS_DIPLOMS_FK1" FOREIGN KEY ("DIPLOM")
	REFERENCES "DIPLOMS" ("OWNER") ON DELETE CASCADE ENABLE, 
	
	CONSTRAINT "EVALUATIONS_USERS_FK1" FOREIGN KEY ("TEACHER")
	REFERENCES "USERS" ("LOGIN") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;